export const CURATED_SKILLS = [
  // === PRODUCTIVITY ===
  {
    slug: 'web-research', name: 'Web Research',
    description: 'Search and synthesize information from the internet',
    longDescription: '# Web Research\n\nPowerful web research skill that searches multiple sources, cross-references information, and synthesizes clear answers with citations.',
    category: 'workflow', subcategory: 'productivity', icon: 'Globe',
    author: 'Kira Team', tags: 'research,search,synthesis,web', isSystem: true, isVerified: true,
    instructions: `# Web Research Skill\n\n## When to activate\nUser asks about current events, needs fact-checking, wants product comparisons, documentation, or any information that benefits from web sources.\n\n## How to execute\n1. Use web_search with a clear, specific query\n2. Review the results — pick the most relevant 2-3\n3. Use web_fetch to read the full content of the best results\n4. Synthesize the information into a clear answer\n5. Always cite your sources with URLs\n\n## Quality standards\n- Never present search results as raw lists — synthesize\n- Cross-reference multiple sources for important claims\n- Note when information might be outdated\n- If search returns nothing useful, say so honestly`,
  },
  {
    slug: 'task-manager', name: 'Task Manager',
    description: 'Create, organize, and track tasks with gamification',
    longDescription: '# Task Manager\n\nSmart task management that extracts tasks from natural conversation, assigns priorities, tracks streaks, and gamifies productivity.',
    category: 'workflow', subcategory: 'productivity', icon: 'CheckSquare',
    author: 'Kira Team', tags: 'tasks,todos,planning,gamification,productivity', isSystem: true, isVerified: true,
    instructions: `# Task Manager Skill\n\n## When to activate\nUser mentions tasks, todos, deadlines, goals, projects, or asks you to track/organize work.\n\n## How to execute\n1. Extract tasks from natural language\n2. When creating tasks, infer priority and due dates from context\n3. Use search_tasks to check for duplicates before creating\n4. Group related tasks under projects\n5. Proactively suggest task breakdowns for complex goals\n\n## Gamification\n- Celebrate task completions\n- Track streaks\n- Note velocity`,
  },
  {
    slug: 'email-drafter', name: 'Email Drafter',
    description: 'Draft professional emails with tone matching and templates',
    longDescription: '# Email Drafter\n\nCraft professional emails that match the right tone for any situation.',
    category: 'micro', subcategory: 'productivity', icon: 'Mail',
    author: 'Kira Team', tags: 'email,writing,communication,professional', isSystem: true, isVerified: true,
    instructions: `# Email Drafter\n\nDraft emails matching the user's tone. Ask for recipient, context, and desired outcome. Offer formal/casual/friendly variants.\n\n## Standards\n- Clear subject lines\n- Appropriate greetings and sign-offs\n- Action items highlighted\n- Concise but complete`,
  },
  {
    slug: 'meeting-prep', name: 'Meeting Prep',
    description: 'Prepare agendas, talking points, and follow-up actions for meetings',
    longDescription: '# Meeting Prep\n\nComprehensive meeting preparation with agendas, talking points, and follow-up emails.',
    category: 'workflow', subcategory: 'productivity', icon: 'Calendar',
    author: 'Kira Team', tags: 'meetings,agenda,preparation,follow-up', isSystem: true, isVerified: true,
    instructions: `# Meeting Prep\n\nGenerate agenda, research attendees, create talking points, draft follow-up emails.`,
  },
  {
    slug: 'note-taker', name: 'Smart Notes',
    description: 'Capture, organize, and connect notes with auto-tagging',
    longDescription: '# Smart Notes\n\nIntelligent note-taking that captures ideas, auto-tags content, and surfaces connections.',
    category: 'micro', subcategory: 'productivity', icon: 'StickyNote',
    author: 'Kira Team', tags: 'notes,organization,capture,knowledge', isSystem: true, isVerified: true,
    instructions: `# Smart Notes\n\nCapture notes, auto-tag, link related notes, surface connections.`,
  },
  // === CODING ===
  {
    slug: 'code-helper', name: 'Code Helper',
    description: 'Write, debug, explain, and execute code in any language',
    longDescription: '# Code Helper\n\nFull-stack coding assistant that writes, runs, debugs, and explains code.',
    category: 'workflow', subcategory: 'coding', icon: 'Code',
    author: 'Kira Team', tags: 'code,programming,debug,development', isSystem: true, isVerified: true,
    instructions: `# Code Helper Skill\n\n## When to activate\nUser asks about code, programming, debugging, or needs something built/automated.\n\n## How to execute\n1. Understand the requirement fully before coding\n2. Use execute_code to write AND run the code\n3. Test your code — run it and verify the output\n4. If there's an error, read it, fix it, and retry\n5. Use read_file/write_file to persist useful scripts\n\n## Quality standards\n- Always run code, never just describe it\n- Handle errors gracefully\n- Comment complex logic\n- Prefer simple, readable solutions`,
  },
  {
    slug: 'code-reviewer', name: 'Code Reviewer',
    description: 'Review code for bugs, security issues, and best practices',
    longDescription: '# Code Reviewer\n\nThorough code review for bugs, security vulnerabilities, and best practices.',
    category: 'micro', subcategory: 'coding', icon: 'Shield',
    author: 'Kira Team', tags: 'code-review,security,quality,best-practices', isSystem: true, isVerified: true,
    instructions: `# Code Reviewer\n\nAnalyze code for: bugs, security vulnerabilities, performance, readability, best practices. Provide actionable feedback.`,
  },
  {
    slug: 'api-builder', name: 'API Builder',
    description: 'Design and build REST/GraphQL APIs with documentation',
    longDescription: '# API Builder\n\nDesign RESTful and GraphQL APIs from scratch with OpenAPI specs and docs.',
    category: 'workflow', subcategory: 'coding', icon: 'Server',
    author: 'Kira Team', tags: 'api,rest,graphql,backend,openapi', isSystem: true, isVerified: true,
    instructions: `# API Builder\n\nDesign endpoints, generate OpenAPI specs, build implementations, create docs.`,
  },
  {
    slug: 'database-designer', name: 'Database Designer',
    description: 'Design schemas, write migrations, optimize queries',
    longDescription: '# Database Designer\n\nExpert database design — normalized schemas, migrations, and query optimization.',
    category: 'workflow', subcategory: 'coding', icon: 'Database',
    author: 'Kira Team', tags: 'database,sql,schema,migration,optimization', isSystem: true, isVerified: true,
    instructions: `# Database Designer\n\nDesign normalized schemas, write migrations, optimize slow queries, explain execution plans.`,
  },
  // === WRITING & CONTENT ===
  {
    slug: 'writing-assistant', name: 'Writing Assistant',
    description: 'Help write, edit, and improve text — emails, docs, posts, copy',
    longDescription: '# Writing Assistant\n\nVersatile writing partner that matches your voice and style.',
    category: 'micro', subcategory: 'writing', icon: 'PenTool',
    author: 'Kira Team', tags: 'writing,editing,copywriting,content', isSystem: true, isVerified: true,
    instructions: `# Writing Assistant Skill\n\n## When to activate\nUser needs help writing, editing, or improving text of any kind.\n\n## How to execute\n1. Understand the audience and purpose\n2. Match the user's voice unless asked otherwise\n3. Provide the full draft, not just suggestions\n4. Offer alternatives for key phrases\n5. Check for clarity, concision, and tone`,
  },
  {
    slug: 'social-media', name: 'Social Media Manager',
    description: 'Create posts, threads, and content calendars for social platforms',
    longDescription: '# Social Media Manager\n\nCreate platform-optimized content for Twitter/X, LinkedIn, Instagram, and TikTok.',
    category: 'workflow', subcategory: 'marketing', icon: 'Share2',
    author: 'Kira Team', tags: 'social,twitter,linkedin,content,marketing', isSystem: true, isVerified: true,
    instructions: `# Social Media Manager\n\nCreate platform-specific content. Twitter: punchy threads. LinkedIn: thought leadership. Instagram: captions. TikTok: hooks.`,
  },
  {
    slug: 'blog-writer', name: 'Blog Writer',
    description: 'Write SEO-optimized blog posts with structure and research',
    longDescription: '# Blog Writer\n\nEnd-to-end blog content creation with SEO optimization.',
    category: 'workflow', subcategory: 'writing', icon: 'FileText',
    author: 'Kira Team', tags: 'blog,seo,content,writing,marketing', isSystem: true, isVerified: true,
    instructions: `# Blog Writer\n\nResearch topic, outline, write with SEO keywords, add meta description, suggest images.`,
  },
  {
    slug: 'translator', name: 'Translator',
    description: 'Translate text between languages with cultural context',
    longDescription: '# Translator\n\nNuanced translation with cultural context, idioms, and formality levels.',
    category: 'micro', subcategory: 'writing', icon: 'Languages',
    author: 'Kira Team', tags: 'translation,languages,localization,international', isSystem: true, isVerified: true,
    instructions: `# Translator\n\nTranslate with cultural nuance, not just literal. Offer formal/informal variants. Flag untranslatable idioms.`,
  },
  // === DATA & ANALYSIS ===
  {
    slug: 'data-analysis', name: 'Data Analysis',
    description: 'Analyze data, create charts, find patterns, generate reports',
    longDescription: '# Data Analysis\n\nComprehensive data analysis — load any format, explore patterns, generate visualizations.',
    category: 'workflow', subcategory: 'data', icon: 'BarChart3',
    author: 'Kira Team', tags: 'data,analysis,charts,statistics,visualization', isSystem: true, isVerified: true,
    instructions: `# Data Analysis Skill\n\n## How to execute\n1. Load/parse the data\n2. Explore: shape, types, missing values, basic stats\n3. Analyze: trends, correlations, outliers\n4. Visualize: generate charts\n5. Summarize findings in plain language`,
  },
  {
    slug: 'spreadsheet-wizard', name: 'Spreadsheet Wizard',
    description: 'Create formulas, pivot tables, and automate Excel/Sheets tasks',
    longDescription: '# Spreadsheet Wizard\n\nMaster of Excel and Google Sheets — complex formulas, pivot tables, and macros.',
    category: 'micro', subcategory: 'data', icon: 'Table',
    author: 'Kira Team', tags: 'excel,sheets,formulas,spreadsheet,automation', isSystem: true, isVerified: true,
    instructions: `# Spreadsheet Wizard\n\nWrite complex formulas, create pivot logic, automate repetitive spreadsheet tasks.`,
  },
  {
    slug: 'report-generator', name: 'Report Generator',
    description: 'Generate professional reports from data with charts and insights',
    longDescription: '# Report Generator\n\nTransform raw data into polished professional reports.',
    category: 'workflow', subcategory: 'data', icon: 'FileBarChart',
    author: 'Kira Team', tags: 'reports,visualization,business-intelligence', isSystem: true, isVerified: true,
    instructions: `# Report Generator\n\nTake raw data, analyze, generate professional reports with charts, executive summary, and recommendations.`,
  },
  // === BUSINESS ===
  {
    slug: 'pitch-deck', name: 'Pitch Deck Builder',
    description: 'Create investor pitch decks with market analysis and financials',
    longDescription: '# Pitch Deck Builder\n\nCraft compelling investor presentations with market research and financial projections.',
    category: 'workflow', subcategory: 'business', icon: 'Presentation',
    author: 'Kira Team', tags: 'pitch,investors,startup,funding,presentation', isSystem: true, isVerified: true,
    instructions: `# Pitch Deck Builder\n\nStructure: Problem → Solution → Market → Traction → Team → Ask.`,
  },
  {
    slug: 'competitor-analysis', name: 'Competitor Analysis',
    description: 'Research and compare competitors with SWOT analysis',
    longDescription: '# Competitor Analysis\n\nDeep competitive intelligence with SWOT analysis and market gap identification.',
    category: 'workflow', subcategory: 'business', icon: 'Target',
    author: 'Kira Team', tags: 'competition,market,strategy,swot,research', isSystem: true, isVerified: true,
    instructions: `# Competitor Analysis\n\nResearch competitors via web, compare features/pricing/positioning, generate SWOT, identify gaps.`,
  },
  {
    slug: 'financial-model', name: 'Financial Modeler',
    description: 'Build revenue projections, unit economics, and financial models',
    longDescription: '# Financial Modeler\n\nBuild bottom-up financial models with revenue projections and scenario analysis.',
    category: 'domain', subcategory: 'finance', icon: 'DollarSign',
    author: 'Kira Team', tags: 'finance,revenue,projections,model,economics', isSystem: true, isVerified: true,
    instructions: `# Financial Modeler\n\nBuild bottoms-up models, calculate unit economics (CAC/LTV/margins), project revenue scenarios.`,
  },
  {
    slug: 'sales-assistant', name: 'Sales Assistant',
    description: 'Qualify leads, draft proposals, and track pipeline',
    longDescription: '# Sales Assistant\n\nEnd-to-end sales support — qualify leads, draft proposals, track deals.',
    category: 'workflow', subcategory: 'business', icon: 'Handshake',
    author: 'Kira Team', tags: 'sales,leads,proposals,crm,pipeline', isSystem: true, isVerified: true,
    instructions: `# Sales Assistant\n\nQualify leads with ICP scoring, draft personalized proposals, suggest follow-up timing, track deal stages.`,
  },
  // === PERSONAL ===
  {
    slug: 'life-coach', name: 'Life Coach',
    description: 'Goal setting, habit tracking, accountability, and personal growth',
    longDescription: '# Life Coach\n\nYour personal accountability partner for goals, habits, and growth.',
    category: 'domain', subcategory: 'personal', icon: 'Target',
    author: 'Kira Team', tags: 'goals,habits,motivation,accountability,growth', isSystem: true, isVerified: true,
    instructions: `# Life Coach Skill\n\n## How to execute\n1. Listen first — understand their situation and goals\n2. Break big goals into actionable steps\n3. Create tasks for next actions\n4. Remember commitments\n5. Follow up on previous commitments\n\n## Standards\n- Be encouraging but honest\n- Focus on systems over willpower\n- Celebrate progress`,
  },
  {
    slug: 'health-tracker', name: 'Health Tracker',
    description: 'Track workouts, meals, sleep, and health metrics',
    longDescription: '# Health Tracker\n\nComprehensive health and fitness tracking with trend analysis.',
    category: 'domain', subcategory: 'health', icon: 'Heart',
    author: 'Kira Team', tags: 'health,fitness,nutrition,sleep,wellness', isSystem: true, isVerified: true,
    instructions: `# Health Tracker\n\nLog workouts/meals/sleep, track trends, suggest improvements, celebrate consistency.`,
  },
  {
    slug: 'budget-planner', name: 'Budget Planner',
    description: 'Track expenses, set budgets, and plan savings goals',
    longDescription: '# Budget Planner\n\nPersonal finance management — track, categorize, budget, and optimize.',
    category: 'domain', subcategory: 'finance', icon: 'Wallet',
    author: 'Kira Team', tags: 'budget,expenses,savings,personal-finance', isSystem: true, isVerified: true,
    instructions: `# Budget Planner\n\nTrack income/expenses, categorize spending, set budgets, calculate savings rate, suggest optimizations.`,
  },
  {
    slug: 'recipe-chef', name: 'Recipe Chef',
    description: 'Find recipes, plan meals, generate shopping lists',
    longDescription: '# Recipe Chef\n\nYour AI sous chef — recipes, meal plans, and shopping lists.',
    category: 'micro', subcategory: 'personal', icon: 'ChefHat',
    author: 'Kira Team', tags: 'cooking,recipes,meal-planning,shopping,food', isSystem: true, isVerified: true,
    instructions: `# Recipe Chef\n\nSuggest recipes based on ingredients/preferences/dietary needs. Generate shopping lists. Scale portions.`,
  },
  {
    slug: 'travel-planner', name: 'Travel Planner',
    description: 'Plan trips with itineraries, bookings, and local tips',
    longDescription: '# Travel Planner\n\nEnd-to-end trip planning with itineraries and budget estimates.',
    category: 'workflow', subcategory: 'personal', icon: 'Plane',
    author: 'Kira Team', tags: 'travel,itinerary,booking,vacation,planning', isSystem: true, isVerified: true,
    instructions: `# Travel Planner\n\nResearch destinations, build day-by-day itineraries, suggest hotels/activities, check visa requirements, estimate budget.`,
  },
  // === LEARNING ===
  {
    slug: 'tutor', name: 'Personal Tutor',
    description: 'Explain concepts, create study plans, quiz and test knowledge',
    longDescription: '# Personal Tutor\n\nAdaptive learning companion that explains, quizzes, and adjusts difficulty.',
    category: 'domain', subcategory: 'learning', icon: 'GraduationCap',
    author: 'Kira Team', tags: 'learning,education,study,tutoring,knowledge', isSystem: true, isVerified: true,
    instructions: `# Personal Tutor\n\nExplain at the user's level, use analogies, create flashcards, quiz knowledge, adapt difficulty.`,
  },
  {
    slug: 'language-learning', name: 'Language Coach',
    description: 'Practice conversations, grammar, vocabulary in any language',
    longDescription: '# Language Coach\n\nImmersive language practice with conversation, corrections, and grammar.',
    category: 'domain', subcategory: 'learning', icon: 'MessageCircle',
    author: 'Kira Team', tags: 'language,practice,vocabulary,grammar,learning', isSystem: true, isVerified: true,
    instructions: `# Language Coach\n\nConverse in target language, correct mistakes gently, teach vocabulary in context, explain grammar rules.`,
  },
  {
    slug: 'book-summarizer', name: 'Book Summarizer',
    description: 'Summarize books with key takeaways and action items',
    longDescription: '# Book Summarizer\n\nDistill any book into key insights, quotes, and action items.',
    category: 'micro', subcategory: 'learning', icon: 'BookOpen',
    author: 'Kira Team', tags: 'books,summary,reading,knowledge,learning', isSystem: true, isVerified: true,
    instructions: `# Book Summarizer\n\nProvide chapter summaries, key insights, memorable quotes, and practical action items from any book.`,
  },
  // === CREATIVE ===
  {
    slug: 'brainstorm', name: 'Brainstorm Partner',
    description: 'Generate ideas, mind maps, and creative solutions',
    longDescription: '# Brainstorm Partner\n\nCreative thinking catalyst using SCAMPER, lateral thinking, and more.',
    category: 'micro', subcategory: 'creative', icon: 'Lightbulb',
    author: 'Kira Team', tags: 'ideas,brainstorm,creativity,innovation', isSystem: true, isVerified: true,
    instructions: `# Brainstorm Partner\n\nGenerate diverse ideas using techniques: SCAMPER, random association, constraint removal. No judgment phase first, then evaluate.`,
  },
  {
    slug: 'storyteller', name: 'Storyteller',
    description: 'Write stories, scripts, and creative fiction',
    longDescription: '# Storyteller\n\nCraft compelling narratives with character development and plot structure.',
    category: 'micro', subcategory: 'creative', icon: 'BookOpen',
    author: 'Kira Team', tags: 'stories,fiction,creative-writing,scripts,narrative', isSystem: true, isVerified: true,
    instructions: `# Storyteller\n\nCraft narratives with character development, plot structure, dialogue. Match genre and tone to request.`,
  },
  // === LEGAL ===
  {
    slug: 'contract-reviewer', name: 'Contract Reviewer',
    description: 'Review contracts and highlight risks, obligations, and key terms',
    longDescription: '# Contract Reviewer\n\nAnalyze contracts for key obligations, risks, and red flags. Not legal advice.',
    category: 'domain', subcategory: 'legal', icon: 'Scale',
    author: 'Kira Team', tags: 'legal,contracts,review,risk,compliance', isSystem: true, isVerified: true,
    instructions: `# Contract Reviewer\n\nAnalyze contracts for: key obligations, termination clauses, liability caps, IP ownership, red flags. NOT legal advice — flag items for attorney review.`,
  },
];
